# Generated by Django 4.1.5 on 2023-01-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mercado", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="product_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mercado.produto",
            ),
            preserve_default=False,
        ),
    ]
