# Generated by Django 4.1.5 on 2023-01-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercado", "0002_price_product_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="price", name="name",),
    ]
