# Generated by Django 4.1.5 on 2023-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercado", "0004_listadecompras"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="link_imagem",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="link_produto",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
