# Generated by Django 4.1.5 on 2023-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercado", "0005_produto_link_imagem_produto_link_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto", name="desconto", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="produto",
            name="description",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="link_suggested",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="name_suggested",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="produto", name="preco", field=models.FloatField(default=0),
        ),
    ]
