# Generated by Django 4.1.5 on 2023-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercado", "0006_produto_desconto_produto_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="produto",
            field=models.CharField(max_length=128),
        ),
    ]
